name: Build

on:
  push:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-app:
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [windows-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            server/target/
          key: ${{ runner.os }}-cargo-${{ matrix.platform }}-${{ hashFiles('api/**/Cargo.lock') }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: cd client && npm ci && npm run build
      - run: cargo test -- --nocapture
        working-directory: server
      - run: cargo build --release
        working-directory: server
      # - run: dir server
      # - run: dir server/target
      # - run: dir server/target/release
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: app-${{ matrix.platform }}
          path: |
            server/target/release/youtube-downloader.exe
            server/target/release/youtube-downloader
